# Generated by Django 4.2.7 on 2025-01-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('icon', models.ImageField(upload_to='icons/', verbose_name='Ícono')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del grupo')),
                ('icon', models.ImageField(upload_to='icons/', verbose_name='Ícono')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Link o Red social')),
                ('icon', models.ImageField(upload_to='icons/', verbose_name='Ícono')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Título del post')),
                ('duration', models.IntegerField(verbose_name='Duración (en minutos)')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto del post (opcional)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen (opcional)')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/', verbose_name='Audio (opcional)')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video (opcional)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Categoría')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.group', verbose_name='Grupo')),
                ('links', models.ManyToManyField(blank=True, null=True, to='blog.link', verbose_name='Links relacionados y redes sociales (opcional)')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
