# Generated by Django 4.2.7 on 2025-01-20 19:44

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_at_post_updated_at_alter_post_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/', validators=[blog.validators.validate_audio_extension], verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='links',
            field=models.ManyToManyField(to='blog.link', verbose_name='Links relacionados y redes sociales'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto del post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[blog.validators.validate_video_extension], verbose_name='Video'),
        ),
    ]
