# Generated by Django 4.2.7 on 2025-01-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_audio_alter_post_image_alter_post_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='links',
            field=models.ManyToManyField(blank=True, to='blog.link', verbose_name='Links relacionados y redes sociales'),
        ),
    ]
