# Generated by Django 4.2.7 on 2025-01-22 01:20

import blog.validators
from django.db import migrations, models
import project.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_category_options_alter_group_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(storage=project.storage_backends.PublicMediaStorage(), upload_to='icons/', verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(storage=project.storage_backends.PublicMediaStorage(), upload_to='icons/', verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.ImageField(storage=project.storage_backends.PublicMediaStorage(), upload_to='icons/', verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=project.storage_backends.PublicMediaStorage(), upload_to='audios/', validators=[blog.validators.validate_audio_extension], verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=project.storage_backends.PublicMediaStorage(), upload_to='images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, storage=project.storage_backends.PublicMediaStorage(), upload_to='videos/', validators=[blog.validators.validate_video_extension], verbose_name='Video'),
        ),
    ]
