# Generated by Django 4.2.7 on 2025-01-22 17:45

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_icon_alter_group_icon_alter_link_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to='icons/', verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(upload_to='icons/', verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.ImageField(upload_to='icons/', verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/', validators=[blog.validators.validate_audio_extension], verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[blog.validators.validate_video_extension], verbose_name='Video'),
        ),
    ]
