# Generated by Django 4.2.7 on 2025-01-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_category_icon_alter_group_icon_alter_link_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField(verbose_name='Duración (en minutos)')),
            ],
            options={
                'verbose_name': 'Duración',
                'verbose_name_plural': 'Duraciones',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.duration', verbose_name='Duración (en minutos)'),
        ),
    ]
