# Generated by Django 4.2.7 on 2025-03-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_duration_alter_post_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Video'),
        ),
    ]
