# Generated by Django 4.2.7 on 2025-03-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_video_post_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio',
        ),
        migrations.AddField(
            model_name='post',
            name='audio_link',
            field=models.URLField(blank=True, null=True, verbose_name='Audio'),
        ),
    ]
